### PR TITLE
Fix/use absolute path in file manipulations

### PR DESCRIPTION
**Pull request by tkngaejcpi**

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
@Luc-Mcgrady @wlckd, does this PR break your workflows? I have tested it in my workflows, and it works well.

**Comment by tkngaejcpi** [comment]
I've just found out I made a mistake in L210: `f.lower().endswith('csv')` which should be `f.lower().endswith('.csv')`.

If you guys merge it, it's something should be additionally fixed and squashed. Or I can drop this PR and create another PR for it.

**Comment by L-M-Sherlock** [comment]
Could you fix it in current PR?

**Comment by tkngaejcpi** [comment]
Of course, I will fix it later :)

**Comment by tkngaejcpi** [comment]
It's done now @L-M-Sherlock

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
