### PR TITLE
Set mean reversion target to D0(4)

### PR DESCRIPTION
**Pull request by user1823**
Supersedes and closes https://github.com/open-spaced-repetition/fsrs-optimizer/pull/123

Coding it like this will allow tweaking the formula further without needing to change the code at two places.

### CODE REVIEW

**Comment by user1823** [comment]
By the way, shouldn't the simulator import the definitions from `fsrs_optimizer.py` instead of defining them again?

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/86eeb694007653b5fcef8e6024871ac819e4a8ae/src/fsrs_optimizer/fsrs_simulator.py#L80-L132

**Comment by L-M-Sherlock** [comment]
Due to type inference problem, it's hard to reuse this function between optimizer and simulator.

By the way, you forget to call the member function as self.init_d.

**Comment by user1823** [comment]
> By the way, you forget to call the member function as self.init_d.

Thanks. If you don't mind, can you briefly explain what is the difference between self.init_d and init_d?

**Comment by user1823** [comment]
> Due to type inference problem, it's hard to reuse this function between optimizer and simulator.

Then, should I make the corrections in the simulator too?

**Comment by user1823** [comment]
I have edited the simulator too.

But, I don't really understand what is `rating_offset`.

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/40376ed1bdafa9cb2884825cae15ca917ef9fb8e/src/fsrs_optimizer/fsrs_simulator.py#L119-L123

**Comment by L-M-Sherlock** [comment]
I make them consistent in the last commit. `rating_offset` is hard to explain. In short, it's used to simulate the effect of short-term reviews.

**Comment by L-M-Sherlock** [comment]
> EDIT: I'm confused, seems like in this case it's not minus 3, but minus 1 instead. Well, hopefully LMSherlock can explain it better.

image

Any problem?

**Comment by user1823** [comment]
I just realized that this is not a bug fix and you deliberately used D0(1) for mean reversion previously.

**Comment by Expertium** [comment]
We recently tried D0(1) vs D0(3) vs D0(4), and they all give almost the same results. RMSE differs in the 4 digit after the decimal point. So LMSherlock decided to go with D0(4)

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
