### PR TITLE
Feat/Command line flag filtering

### LINKED ISSUE #24: Command Line typo on usage section fsrs-optimizer doesn't exist [BUG]
**Describe the bug**
there is a typo on the 2.1c Command Line wiki in the usage section, module name it's fsrs_optimizer instead of fsrs-optimizer 

**Additional context**
Also by the way, filter_out_flags = [] option is missing, it is because the module works with a former version of the optimizer? 
thanks for the hard work :)

### PR DESCRIPTION
**Pull request by Luc-Mcgrady**
closes #24 
```
$ python __main__.py --help
  --flags FLAGS [FLAGS ...]
                        Remove any cards with the given flags from the training set.
```
Haven't actually tested it but it passes the flags to the `filter_out_flags` argument of the `optimizer.anki_extract`.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Could you provide a use case?

**Comment by Luc-Mcgrady** [comment]
I dont know its just what I thought @cocowash asked for in #24.

**Comment by L-M-Sherlock** [comment]
> I dont know its just what I thought @cocowash asked for in #24.

I mean, should I use `--flags 1 2 3` or `--flags [1, 2, 3]`?

**Comment by Luc-Mcgrady** [comment]
The first one

**Comment by Luc-Mcgrady** [comment]
```python __main__.py *.apkg --flags 1 2 3```
This is the command I used to check it worked.

**Review by L-M-Sherlock — APPROVED** [review]

**Pull request merged**
