### PR TITLE
Feat/FSRS-5 [WIP]

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
candidate:
- #81
- #110 

I plan to release FSRS-5 in June.

### CODE REVIEW

**Comment by Expertium** [comment]
> I plan to release FSRS-5 in June.

I think that instead of aiming for "release FSRS-5 in [month]", we should aim for "release when RMSE decreases by at least 10% relative to FSRS-4.5"

**Comment by L-M-Sherlock** [comment]
> I think that instead of aiming for "release FSRS-5 in [month]", we should aim for "release FSRS-5 when RMSE decreases by at least 10% relative to FSRS-4.5"

I'm afraid FSRS-5 will be never released if we need to achieve that target.

- FSRS-4.5 was released 5 months ago.
- FSFSv4 was released 10 months ago.
- FSFSv3 was released 20 months ago.

I think it's a good time to release FSRS-5.

**Comment by Expertium** [comment]
With all due respect, I don't understand why you feel the need to release a new version if it's barely an improvement compared to the previous version. I firmly believe that we should aim for at least 10%. More would be better, of course. To me, 10% seems like the bare minimum; below that point, it's just not worth bothering with releasing a new version.

**Comment by Expertium** [comment]
@user1823 out of curiosity, what's your opinion?

**Comment by user1823** [comment]
As the algorithm improves, the scope for further improvement decreases. So, aiming for a 10% improvement every time is not feasible.

If the algorithm is going to consider short-term reviews now, I believe that this is a significant change and the update deserves to be called v5.

**Comment by ishiko732** [comment]
I noticed that there is a change in the `DEFAULT_PARAMETER` length. How should migrate from FSRSv4.5 to FSRSv5? Do  just need to add the default parameters w[17] and w[18]?

**Comment by Expertium** [comment]
> As the algorithm improves, the scope for further improvement decreases. So, aiming for a 10% improvement every time is not feasible.

Of course, but then the question is: should we not release a new version, or release a new version even though the improvement is small? I think the former makes more sense. If we choose the latter, we might end up with something like FSRS-10, where the improvement is so small that it's barely detectable even on the 20k dataset.

**Comment by user1823** [comment]
> if by October we won't find a way to decrease RMSE by >=10%, we will release FSRS-5 in October, otherwise we will release it earlier?

Makes sense. I agree that we don't need to rush through the release.

**Comment by L-M-Sherlock** [comment]
> if by October we won't find a way to decrease RMSE by >=10%, we will release FSRS-5 in October, otherwise we will release it earlier?

OK.

I have some criteria for the ideas:
1. If the idea introduce extra parameters, the improvement should be greater than 2% per param.
2. It should respect the current definition and range of stability and difficulty.
3. It should be compatible with the old parameters.

**Comment by Expertium** [comment]
> 1. If the idea introduce extra parameters, the improvement should be greater than 2% per param.

That's gonna be hard.

> 2. It should respect the current definition and range of stability and difficulty.

Does that mean that my new defnition of D (based on R) is automatically disqualified?

> 3. It should be compatible with the old parameters.

What do you mean exactly?

**Comment by L-M-Sherlock** [comment]
> Does that mean that my new definition of D (based on R) is automatically disqualified?

If your new definition of D is out of the range 1~10, it would be rejected.

> What do you mean exactly?

The user could use the new parameters without rescheduling all their cards.

**Comment by Expertium** [comment]
> The user could use the new parameters without rescheduling all their cards.

This one will always be satisfied, no? I mean, the user will have to click "Optimize" to obtain new parameters, but won't have to reschedule. How would it be different?

**Comment by Expertium** [comment]
`forget_rating_offest=-0.1`

Typo, it should be `forget_rating_offset`. Btw, what does it do?

**Comment by L-M-Sherlock** [comment]
> Typo, it should be `forget_rating_offset`. Btw, what does it do?

Sometime the user may press `again` during the relearning step, it will reduce the stability in FSRS-5. The `forget_rating_offset` is used to simulate it.

**Comment by Expertium** [comment]
Why not just record 4 values of answer buttons, but for learning and re-learning steps?

**Comment by L-M-Sherlock** [comment]
> Why not just estimate 4 values of answer button probabilities, but for learning and re-learning steps?

It's computing-expensive and hard to model.

**Comment by Expertium** [comment]
Is it? It's just another numpy array (and whatever equivalent of a numpy array is used in Rust), similar to `first_rating_prob`

**Comment by L-M-Sherlock** [comment]
> Is it? It's just another numpy array (and whatever equivalent of a numpy array is used in Rust), similar to `first_rating_prob`. maybe you misunderstood me, I meant "Make an array with 4 values, like `first_rating_prob`, but for probabilities of pressing Again/Hard/Goode/Easy in (re)learning"

The user may not only press once. The short-term rating sequence would be `1,2,2,3`, `1,3`, `1,4`, `1,1,3,1,3` and so on.

**Comment by Expertium** [comment]
I don't see forget_rating_offset here: https://github.com/ankitects/anki/pull/3298

**Pull request merged**
