### PR TITLE
Feat/save plot files to local directory

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
@topherbuckley could you help me test this feature?

**Comment by Luc-Mcgrady** [comment]
image
Works for me 👍
Much less obtrusive than having the graphs pop-up.
Maybe include the deck name in the filenames as it overwrites them if you do more than one deck at once.

**Comment by Luc-Mcgrady** [comment]
Testing multiple decks at once I get this warning.

/home/luc/Programming/forks/fsrs-optimizer/src/fsrs_optimizer/fsrs_optimizer.py:286: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

Looks like you just need to close the decks after you save them

**Comment by topherbuckley** [comment]
Tested on one deck so far, and worked as expected. How did you test multiple decks? I have a bash loop like this:
```bash
#!/bin/bash

# Get a list of all files in the current directory ending with ".apkg"
file_list=$(ls *.apkg 2>/dev/null)

# Check if there are any files with the ".apkg" extension
if [ -z "$file_list" ]; then
  echo "No files with '.apkg' extension found in the current directory."
  exit 1
fi

# Loop through each file in the list
for file in $file_list; do
  echo "Processing file: $file"
  
  # Execute the Python command with the current file as "X"
  python -m fsrs4_optimizer "$file" -y -o weights
  
  echo "Finished processing $file"
  echo
done
```
Is that what you had in mind for a test for multiple? 

The only input I'd give for now though is to either default to .svg or give a command-line prompt asking if the user wants to save as .png or .svg. SVG is a vector graphics format so it tends to be less in size, and better quality. Other than that, looks great so far. Thanks for the quick turn around on this! I'll set my bash loop to run and let you know if it runs into any issues later.

**Comment by Luc-Mcgrady** [comment]
You can just list multiple files

```python -m fsrs4_optimizer file1.akpg file2.apkg```

or alternatively with wildcards

```python -m fsrs4_optimizer *.apkg```

**Comment by topherbuckley** [comment]
> You can just list multiple files
> 
> `python -m fsrs4_optimizer file1.akpg file2.apkg`
> 
> or alternatively with wildcards
> 
> `python -m fsrs4_optimizer *.apkg`

Thanks! Last time I read the readme it said those weren't supported. Got it. 

My loop just finished without issue. So it appears to be working as expected. Thanks!

**Pull request merged**
