### PR TITLE
Fix/Don't remove rows with mean R = 1

### PR DESCRIPTION
**Pull request by user1823**
Fixes https://github.com/open-spaced-repetition/fsrs-optimizer/issues/69

Filtering out the delta_t whose mean_recall = 1 is not a good idea because this can cause the optimizer to throw away a lot of useful data. R=1 doesn't necessarily imply that the mean is based on a very small number of reviews (like 1 or 2 reviews).

We use additive smoothing, which means that R will never be _exactly_ 0% or 100% in the pretrain data. So, we don't need to remove such rows.

The rows that actually have a very small count are already removed by the outlier filter. So, we also don't need to worry about such rows getting a weird R due to the additive smoothing and making the estimation of S0 inaccurate.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
I insist to remove these data.

**Comment by Expertium** [comment]
I agree with user1823, additive smoothing already solves this issue (as well as R=0%)

**Comment by user1823** [comment]
> The rows that actually have a very small count are already removed by the outlier filter. So, we also don't need to worry about such rows getting a weird R due to the additive smoothing and making the estimation of S0 inaccurate.

If you think that the current outlier filter wouldn't be able to remove the rows that have a very low `count` in the cases where `total_count` is also low, we can change the line 649 to something like

```py
                if has_been_removed + count >= max(total * 0.05, 20):
```

This change will make the outlier filter more efficient in removing rows with low count.

**Comment by L-M-Sherlock** [comment]
The current method is not enough when the user has many rows with low count. For example:

```

0          4       1  1.000000    12
1          4       2  0.900000    10
2          4       3  1.000000    11
3          4       4  1.000000    19
4          4       5  0.894737    19
5          4       6  1.000000     5
6          4       7  1.000000     4
7          4       8  1.000000     3
8          4      10  1.000000     2
9          4      11  0.666667     3
10         4      12  1.000000    10
11         4      13  1.000000     7
12         4      14  0.857143     7
13         4      15  1.000000    11
14         4      16  1.000000     4
15         4      17  1.000000     2
16         4      18  1.000000     6
17         4      20  0.666667     3
18         4      22  1.000000     3
19         4      26  1.000000     1
20         4      28  1.000000     3
21         4      32  1.000000     1
22         4      33  1.000000     1
23         4      35  1.000000     1
24         4      40  0.000000     1
25         4      41  1.000000     1
26         4     156  1.000000     1
27         4     251  1.000000     1
28         4     370  0.000000     2
29         4     420  0.000000     1
30         4     487  1.000000     1
```

In this case, the current filter will remove nothing.

> This change will make the outlier filter more efficient in removing rows with low count.

It doesn't work if the number of rows is greater than 20.

**Comment by user1823** [comment]
You have a valid point. What's your opinion about my latest change? It ensures that all rows with count upto 5 are removed.

**Comment by L-M-Sherlock** [comment]
Seems better. But I will not re-run the benchmark. It has cost me too much time.

**Review by L-M-Sherlock — APPROVED** [review]

**Pull request merged**
