### PR TITLE
Feat/sse median in calculating recall cost, forget cost and learn cost

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by Expertium** [comment]
Are zeros removed? As user1823 said, we should remove all values that are precisely equal to 0.

**Comment by L-M-Sherlock** [comment]
> Are zeros removed? As user1823 said, we should remove all values that are precisely equal to 0.

Should these revlogs be removed in training?

**Comment by Expertium** [comment]
No, I meant that if review time=0 ms, it should be excluded from the median calculation. Though it might be a good idea to exclude them from everything.
@user1823 thoughts?

**Comment by L-M-Sherlock** [comment]
Now zero values have been removed in calculating the cost.

**Comment by user1823** [comment]
I can't verify the accuracy of the code but broadly it looks good to me.

**Comment by user1823** [comment]
Wait a minute, I couldn't find anything that removes the reviews with time > 20 min.

**Review by Expertium — APPROVED** [review]

**Comment by L-M-Sherlock** [comment]
Thanks for reviews!

**Pull request merged**
